"""Add character_id into ArenaInfo model

Revision ID: 7dfff4099664
Revises: 79f2e5980b4b
Create Date: 2023-08-03 03:38:05.676994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfff4099664'
down_revision = '79f2e5980b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_info', sa.Column('character_id', sa.Integer(), nullable=False))
    op.alter_column('arena_info', 'cp',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arena_info', 'cp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('arena_info', 'character_id')
    # ### end Alembic commands ###
