"""Regenerate whole schema

Revision ID: aedece200624
Revises: 
Create Date: 2023-08-09 02:52:14.091997

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aedece200624'
down_revision = None
branch_labels = None
depends_on = None

arena_type = postgresql.ENUM('OffSeason', 'Season', 'Championship', name='arenatype', create_type=False)
stat_type = postgresql.ENUM(
    'NONE', 'HP', 'ATK', 'DEF', 'CRI', 'HIT', 'SPD', 'DRV', 'DRR', 'CDMG', 'APTN', 'THORN',
    name='stattype', create_type=False
)
item_type = postgresql.ENUM('CONSUMABLE', 'COSTUME', 'EQUIPMENT', 'MATERIAL', name='itemtype', create_type=False)
item_subtype = postgresql.ENUM(
    'FOOD',
    'FULL_COSTUME', 'HAIR_COSTUME', 'EAR_COSTUME', 'EYE_COSTUME', 'TAIL_COSTUME',
    'WEAPON', 'ARMOR', 'BELT', 'NECKLACE', 'RING',
    'EQUIPMENT_MATERIAL', 'FOOD_MATERIAL', 'MONSTER_PART', 'NORMAL_MATERIAL',
    'HOURGLASS', 'AP_STONE',
    'CHEST',  # Obsoleted
    'TITLE',
    name='itemsubtype', create_type=False)
elemental_type = postgresql.ENUM('NORMAL', 'FIRE', 'WATER', 'LAND', 'WIND',
                                 name='elementaltype', create_type=False)
skill_type = postgresql.ENUM("SKILL", "BUFF_SKILL", name="skilltype", create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    arena_type.create(op.get_bind(), checkfirst=False)
    stat_type.create(op.get_bind(), checkfirst=False)
    item_type.create(op.get_bind(), checkfirst=False)
    item_subtype.create(op.get_bind(), checkfirst=False)
    elemental_type.create(op.get_bind(), checkfirst=False)
    skill_type.create(op.get_bind(), checkfirst=False)

    op.create_table('arena',
                    sa.Column('championship', sa.Integer(), nullable=False),
                    sa.Column('round', sa.Integer(), nullable=False),
                    sa.Column('arena_type', arena_type, nullable=False),
                    sa.Column('start_block_index', sa.BigInteger(), nullable=False),
                    sa.Column('end_block_index', sa.BigInteger(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('arena_championship_round_idx', 'arena', ['championship', 'round'], unique=False)
    op.create_table('block',
                    sa.Column('index', sa.Integer(), nullable=False),
                    sa.Column('hash', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('index')
                    )
    op.create_index(op.f('ix_block_index'), 'block', ['index'], unique=False)
    op.create_table('character_sheet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('hp', sa.Integer(), nullable=False),
                    sa.Column('atk', sa.Integer(), nullable=False),
                    sa.Column('dfc', sa.Integer(), nullable=False),
                    sa.Column('cri', sa.Integer(), nullable=False),
                    sa.Column('hit', sa.Integer(), nullable=False),
                    sa.Column('spd', sa.Integer(), nullable=False),
                    sa.Column('lv_hp', sa.Float(), nullable=False),
                    sa.Column('lv_atk', sa.Float(), nullable=False),
                    sa.Column('lv_dfc', sa.Float(), nullable=False),
                    sa.Column('lv_cri', sa.Float(), nullable=False),
                    sa.Column('lv_hit', sa.Float(), nullable=False),
                    sa.Column('lv_spd', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('costume_stat_sheet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('costume_id', sa.Integer(), nullable=False),
                    sa.Column('type', stat_type, nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('equipment_item_sheet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('type', stat_type, nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rune_option_sheet',
                    sa.Column('rune_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('cp', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('rune_id_name_idx', 'rune_option_sheet', ['rune_id', 'level'], unique=False)
    op.create_table('arena_info',
                    sa.Column('avatar_addr', sa.Text(), nullable=False),
                    sa.Column('agent_addr', sa.Text(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('character_id', sa.Integer(), nullable=False),
                    sa.Column('cp', sa.Integer(), nullable=False),
                    sa.Column('costume_armor_id', sa.Integer(), nullable=False),
                    sa.Column('title_id', sa.Integer(), nullable=True),
                    sa.Column('arena_id', sa.Integer(), nullable=False),
                    sa.Column('win', sa.Integer(), nullable=False),
                    sa.Column('lose', sa.Integer(), nullable=False),
                    sa.Column('ticket', sa.Integer(), nullable=False),
                    sa.Column('ticket_reset_count', sa.Integer(), nullable=False),
                    sa.Column('purchased_ticket_count', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['arena_id'], ['arena.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('avatar_arena_id_idx', 'arena_info', ['avatar_addr', 'arena_id'], unique=False)
    op.create_table('costume',
                    sa.Column('item_id', sa.Text(), nullable=True),
                    sa.Column('arena_info_id', sa.Integer(), nullable=False),
                    sa.Column('sheet_id', sa.Integer(), nullable=False),
                    sa.Column('item_type', item_type, nullable=True),
                    sa.Column('item_subtype', item_subtype, nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['arena_info_id'], ['arena_info.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('equipment',
                    sa.Column('item_id', sa.Text(), nullable=True),
                    sa.Column('arena_info_id', sa.Integer(), nullable=False),
                    sa.Column('sheet_id', sa.Integer(), nullable=False),
                    sa.Column('item_type', item_type, nullable=True),
                    sa.Column('item_subtype', item_subtype, nullable=True),
                    sa.Column('elemental_type', elemental_type, nullable=True),
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('set_id', sa.Integer(), nullable=True),
                    sa.Column('stat_type', stat_type, nullable=True),
                    sa.Column('stat_value', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['arena_info_id'], ['arena_info.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rune',
                    sa.Column('rune_id', sa.Integer(), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('arena_info_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['arena_info_id'], ['arena_info.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('rune_id_level_idx', 'rune', ['rune_id', 'level'], unique=False)
    op.create_table('equipment_stat',
                    sa.Column('equipment_id', sa.Integer(), nullable=False),
                    sa.Column('stat_type', stat_type, nullable=False),
                    sa.Column('stat_value', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('skill',
                    sa.Column('type', skill_type, nullable=False),
                    sa.Column('equipment_id', sa.Integer(), nullable=False),
                    sa.Column('skill_id', sa.Integer(), nullable=False),
                    sa.Column('referenced_stat_type', stat_type, nullable=True),
                    sa.Column('stat_power_ratio', sa.Integer(), nullable=True),
                    sa.Column('power', sa.Integer(), nullable=True),
                    sa.Column('chance', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    op.drop_table('equipment_stat')
    op.drop_index('rune_id_level_idx', table_name='rune')
    op.drop_table('rune')
    op.drop_table('equipment')
    op.drop_table('costume')
    op.drop_index('avatar_arena_id_idx', table_name='arena_info')
    op.drop_table('arena_info')
    op.drop_index('rune_id_name_idx', table_name='rune_option_sheet')
    op.drop_table('rune_option_sheet')
    op.drop_table('equipment_item_sheet')
    op.drop_table('costume_stat_sheet')
    op.drop_table('character_sheet')
    op.drop_index(op.f('ix_block_index'), table_name='block')
    op.drop_table('block')
    op.drop_index('arena_championship_round_idx', table_name='arena')
    op.drop_table('arena')

    skill_type.drop(op.get_bind(), checkfirst=False)
    elemental_type.drop(op.get_bind(), checkfirst=False)
    item_subtype.drop(op.get_bind(), checkfirst=False)
    item_type.drop(op.get_bind(), checkfirst=False)
    stat_type.drop(op.get_bind(), checkfirst=False)
    arena_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
