"""Create arena, avatar, block, sheet models

Revision ID: b4abe38403e5
Revises: 
Create Date: 2023-07-26 23:39:39.067719

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4abe38403e5'
down_revision = None
branch_labels = None
depends_on = None

arena_type_enum = postgresql.ENUM('OffSeason', 'Season', 'Championship', name='arenatype', create_type=False)
stat_type_enum = postgresql.ENUM('HP', 'ATK', 'DEF', 'CRI', 'HIT', 'SPD', 'DRV', 'DRR', 'CDMG', 'APTN', 'THORN',
                                 name='stattype', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    arena_type_enum.create(op.get_bind(), checkfirst=False)
    stat_type_enum.create(op.get_bind(), checkfirst=False)
    op.create_table('arena',
                    sa.Column('championship', sa.Integer(), nullable=False),
                    sa.Column('round', sa.Integer(), nullable=False),
                    sa.Column('arena_type', arena_type_enum, nullable=False),
                    sa.Column('start_block_index', sa.BigInteger(), nullable=False),
                    sa.Column('end_block_index', sa.BigInteger(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('arena_championship_round_idx', 'arena', ['championship', 'round'], unique=False)
    op.create_table('avatar',
                    sa.Column('addr', sa.Text(), nullable=False),
                    sa.Column('agent_addr', sa.Text(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('costume_armor_id', sa.Integer(), nullable=False),
                    sa.Column('title_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('addr')
                    )
    op.create_index(op.f('ix_avatar_addr'), 'avatar', ['addr'], unique=False)
    op.create_table('block',
                    sa.Column('index', sa.Integer(), nullable=False),
                    sa.Column('hash', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('index')
                    )
    op.create_index(op.f('ix_block_index'), 'block', ['index'], unique=False)
    op.create_table('character_sheet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('hp', sa.Integer(), nullable=False),
                    sa.Column('atk', sa.Integer(), nullable=False),
                    sa.Column('dfc', sa.Integer(), nullable=False),
                    sa.Column('cri', sa.Integer(), nullable=False),
                    sa.Column('hit', sa.Integer(), nullable=False),
                    sa.Column('spd', sa.Integer(), nullable=False),
                    sa.Column('lv_hp', sa.Float(), nullable=False),
                    sa.Column('lv_atk', sa.Float(), nullable=False),
                    sa.Column('lv_dfc', sa.Float(), nullable=False),
                    sa.Column('lv_cri', sa.Float(), nullable=False),
                    sa.Column('lv_hit', sa.Float(), nullable=False),
                    sa.Column('lv_spd', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('costume_stat_sheet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', stat_type_enum, nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('equipment_item_sheet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('type', stat_type_enum, nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rune_option_sheet',
                    sa.Column('rune_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('cp', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('rune_id_name_idx', 'rune_option_sheet', ['rune_id', 'level'], unique=False)
    op.create_table('arena_info',
                    sa.Column('avatar_addr', sa.Text(), nullable=False),
                    sa.Column('arena_id', sa.Integer(), nullable=False),
                    sa.Column('win', sa.Integer(), nullable=False),
                    sa.Column('lose', sa.Integer(), nullable=False),
                    sa.Column('ticket', sa.Integer(), nullable=False),
                    sa.Column('ticket_reset_count', sa.Integer(), nullable=False),
                    sa.Column('purchased_ticket_count', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['arena_id'], ['arena.id'], ),
                    sa.ForeignKeyConstraint(['avatar_addr'], ['avatar.addr'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arena_info')
    op.drop_index('rune_id_name_idx', table_name='rune_option_sheet')
    op.drop_table('rune_option_sheet')
    op.drop_table('equipment_item_sheet')
    op.drop_table('costume_stat_sheet')
    op.drop_table('character_sheet')
    op.drop_index(op.f('ix_block_index'), table_name='block')
    op.drop_table('block')
    op.drop_index(op.f('ix_avatar_addr'), table_name='avatar')
    op.drop_table('avatar')
    op.drop_index('arena_championship_round_idx', table_name='arena')
    op.drop_table('arena')
    stat_type_enum.drop(op.get_bind(), checkfirst=False)
    arena_type_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
